// header file for all utility functionss
#ifndef UTILITIES_H
#define UTILITIES_H

#include <chrono>
#include <iomanip>
#include <sstream>
#include "Hash_Table.h"
#include "student.h"
#include "book.h"


//functions to populate the hash table instances with vectors generated by parser
//FOR STUDENTS
void populateStudentHashTable(HashTable<Student>& studentTable, const std::vector<Student>& students);

//FOR BOOKS
void populateBookHashTable(HashTable<Book>& bookTable, const std::vector<Book>& books);

//get current date in the format "dd-mm-yyyy"
std::string getCurrentDate();

//get date two weeks from current date in the format "dd-mm-yyyy"
std::string getTwoWeeksLaterDate();



#endif 
